### ISSUE TITLE
null is treated as undefined

### ISSUE THREAD

**Issue by danielroe** [nuxt-contrib/defu#12]
When passing in a new object where some of the properties are `null`, the defaults are used instead. I would expect this only be true for `undefined` properties.

Repro: https://codesandbox.io/s/defu-repro-o1l04

**Comment by pi0** [comment]
Hi, @danielroe thanks for making the issue.

This is by design that null being skipped as `defu` was originally written based to be defaults-deep spect compatible and actually for option defaults I think makes sense to disable options via explicit boolean.

I did research these are modules ignoring null:
- defu
- defaults-deep
- assign-deep
- extend-shallow
- merge-deep
- mixin-deep

Modules not ignoring null:
- omit-deep
- lodash.defaultsdeep
